const QUIZ_DATA = {
  "D1": {
    "id": "D1",
    "name": "Cloud Concepts, Architecture and Design",
    "questions": [
      {"id": 1, "question": "Which cloud computing characteristic allows customers to manage their utilization by only paying for the resources used?", "choices": ["Metered service", "Broad network access", "Rapid elasticity", "On-demand self-service"], "answerIndex": 0},
      {"id": 2, "question": "Which cloud deployment model allows customers to take advantage of service and price differences from two or more cloud vendors?", "choices": ["Public cloud", "Hybrid cloud", "Multi-cloud", "Private cloud"], "answerIndex": 2},
      {"id": 3, "question": "Which cloud consideration refers to the ability of the infrastructure to withstand disruptive events?", "choices": ["Governance", "Availability", "Resiliency", "Maintenance"], "answerIndex": 2},
      {"id": 4, "question": "An organization discovers its data will be stored in a proprietary data format that cannot be read by other cloud services. Which cloud risk does this represent?", "choices": ["Regulatory failure", "Inadvertent disclosure", "Vendor lock-in", "Data seizure"], "answerIndex": 2},
      {"id": 5, "question": "A company configures a backup solution that syncs data between multiple cloud service providers, but the providers may not have the same level of data protection or allow direct syncing. Which architectural concept addresses this concern?", "choices": ["Interoperability", "Availability", "Resiliency", "Scalability"], "answerIndex": 0},
      {"id": 6, "question": "Which design pillar represents the ability of a workload to execute its intended function accurately and consistently when it is expected to?", "choices": ["Security", "Operational excellence", "Cost optimization", "Reliability"], "answerIndex": 3},
      {"id": 7, "question": "A group of colleges decided to pool their resources to create a community cloud. Which risk is associated with this type of cloud deployment?", "choices": ["Proprietary data formats preventing data conversion", "A lack of compliance with relevant regulations", "Shared access and control mechanisms between members", "Decreased visibility of cloud performance and resource usage"], "answerIndex": 2},
      {"id": 8, "question": "Which NIST publication establishes the standard global definition of cloud computing, including the 5 essential characteristics, 3 service models, and 4 deployment models?", "choices": ["NIST 800-37", "NIST 800-146", "NIST 800-145", "NIST 500-292"], "answerIndex": 2},
      {"id": 9, "question": "A cloud customer wants fundamental computing building blocks such as virtual servers, raw network routing, and block storage, while retaining control over the OS and applications. Which service model best fits this need?", "choices": ["SaaS", "PaaS", "IaaS", "FaaS"], "answerIndex": 2},
      {"id": 10, "question": "Which cloud deployment model is provisioned exclusively for a group of organizations that share a mission, policy requirements, or compliance needs?", "choices": ["Public", "Private", "Community", "Hybrid"], "answerIndex": 2},
      {"id": 11, "question": "An organization becomes so reliant on a cloud provider's proprietary APIs and data formats that migrating away becomes cost-prohibitive. Which risk does this describe?", "choices": ["Vendor lock-out", "Vendor lock-in", "Multitenancy risk", "Data residency risk"], "answerIndex": 1},
      {"id": 12, "question": "Which framework defines the distribution of security responsibilities between the cloud service provider and the cloud customer based on the service model selected?", "choices": ["Cloud Controls Matrix", "Shared responsibility model", "Trusted Cloud Initiative Reference Model", "CAIQ"], "answerIndex": 1},
      {"id": 13, "question": "Which cloud characteristic allows consumers to unilaterally provision computing capabilities such as server time or storage without requiring human interaction with the provider?", "choices": ["Resource pooling", "Broad network access", "On-demand self-service", "Rapid elasticity"], "answerIndex": 2}
    ]
  },
  "D2": {
    "id": "D2",
    "name": "Cloud Data Security",
    "questions": [
      {"id": 1, "question": "Which phase of the cloud data life cycle requires adherence to export and import restrictions, including Export Administration Regulations (EAR) and the Wassenaar Arrangement?", "choices": ["Create", "Share", "Use", "Destroy"], "answerIndex": 1},
      {"id": 2, "question": "What is the purpose of egress monitoring tools?", "choices": ["They are used to convert a given set of data or information into a different value.", "They are used to prevent data from going outside the control of an organization.", "They are used to create data during the Create phase of the cloud data life cycle.", "They are used to remove data during the Destroy phase of the cloud data life cycle."], "answerIndex": 1},
      {"id": 3, "question": "An organization needs to store passwords in a database securely. The data should not be available to system administrators. Which technique should the organization use?", "choices": ["Encryption", "Hashing", "Encoding", "Masking"], "answerIndex": 1},
      {"id": 4, "question": "A company wants to ensure that the names of individuals in its data in the cloud are not revealed in the event of a data breach. Which data masking technique should the company use to prevent attackers from identifying individuals?", "choices": ["Crypto-shredding", "Degaussing", "Anonymization", "Randomization"], "answerIndex": 2},
      {"id": 5, "question": "An organization needs to quickly identify the document owner in a shared network folder. Which technique should the organization use?", "choices": ["Labeling", "Classification", "Mapping", "Categorization"], "answerIndex": 0},
      {"id": 6, "question": "An organization plans to introduce a new data standard and wants to ensure that system inventory data will be efficiently discovered and processed. Which type of data should the organization use?", "choices": ["Structured", "Semi-structured", "Annotated", "Mapped"], "answerIndex": 1},
      {"id": 7, "question": "An organization implemented an information rights management (IRM) solution to prevent critical data from being copied without permission and a cloud backup solution to protect the data from storage failures. Which IRM challenge will the organization need to address?", "choices": ["Jurisdictional conflicts", "Agent conflicts", "Replication restrictions", "Execution restrictions"], "answerIndex": 2},
      {"id": 8, "question": "A data center engineer is tasked with the destruction of data on solid-state drives (SSDs) and must ensure the data cannot be retrieved. Which data destruction action should the engineer take?", "choices": ["Overwriting", "Crypto-shredding", "Wiping", "Degaussing"], "answerIndex": 1}
    ]
  },
  "D3": {
    "id": "D3",
    "name": "Cloud Platform and Infrastructure Security",
    "questions": [
      {"id": 1, "question": "Why is the striping with parity method of storing data used in most redundant array of independent disks (RAID) configurations?", "choices": ["It prevents outages and attacks from occurring in a cloud environment.", "It prevents data from being recovered once it is destroyed using crypto-shredding.", "It allows data to be safely distributed and stored in a common centralized location.", "It allows efficient data recovery as even if one drive fails, other drives fill in the missing data."], "answerIndex": 3},
      {"id": 2, "question": "A company is looking at different types of cloud storage options. One threat is the possibility of losing forensic artifacts in the event of an incident response investigation. Which type of cloud storage has the highest risk of losing forensic artifacts?", "choices": ["File-based", "Long-term", "Block", "Ephemeral"], "answerIndex": 3},
      {"id": 3, "question": "Which software type allows multiple operating systems to run on the same physical server in a virtualized environment?", "choices": ["Hypervisor", "Container", "Quantum computing", "Blockchain technology"], "answerIndex": 0},
      {"id": 4, "question": "What is the name of the process of automatically provisioning, configuring, and managing virtual machines and other resources in a virtualized environment?", "choices": ["Continuous deployment", "Orchestration", "Programmability", "Continuous integration"], "answerIndex": 1},
      {"id": 5, "question": "Which safety control acts as a virtual firewall in cloud environments?", "choices": ["Traffic inspection", "Zero trust", "Network security group", "Geofencing"], "answerIndex": 2}
    ]
  },
  "D4": {
    "id": "D4",
    "name": "Cloud Application Security",
    "questions": [
      {"id": 1, "question": "A cloud customer wants to store API tokens for their applications so they can be accessed from anywhere. Which cloud provider service should the customer use?", "choices": ["Secrets management", "Multifactor authentication", "Single sign-on", "Federated identity"], "answerIndex": 0},
      {"id": 2, "question": "Which type of management focuses on arranging all the elements needed to deploy new software, including QA testing and staging, before the software enters active maintenance?", "choices": ["Availability management (AM)", "Release management (RM)", "Incident management (IM)", "Problem management (PM)"], "answerIndex": 1},
      {"id": 3, "question": "An organization's engineers attended training on the dangers of using insecure direct object identifiers to view another user's account information. Which OWASP Top 10 vulnerability category did their training cover?", "choices": ["Vulnerable and outdated components", "Identification and authentication failures", "Broken access control", "Security logging failures"], "answerIndex": 2},
      {"id": 4, "question": "An organization's engineers attended training on the dangers of using weak algorithms or protocols for data security. Which OWASP Top 10 vulnerability category did their training cover?", "choices": ["Insecure design", "Hashing", "Sandboxing", "Cryptographic failures"], "answerIndex": 3},
      {"id": 5, "question": "A company hires an IT security consultant to perform a zero-knowledge test to access the application as an external hacker would. Which testing technique applies to this work?", "choices": ["Black box", "White box", "Abuse case", "Static application"], "answerIndex": 0},
      {"id": 6, "question": "Which concept refers to multiple teams and roles within an organization that perform testing on code from end to end to ensure that the code meets all standards and requirements?", "choices": ["Quality assurance", "Identity assurance", "Full tests", "Tabletop tests"], "answerIndex": 0},
      {"id": 7, "question": "What is the purpose of implementing rate limiting in API security?", "choices": ["To reduce API response time", "To block unauthorized API access", "To prevent API overuse", "To increase API usage"], "answerIndex": 2},
      {"id": 8, "question": "An organization wants to ensure that untested software updates provided by a third-party vendor are not run in its mission-critical environment. What should the organization use in this scenario?", "choices": ["Automatic updates", "Update notifications", "Update documentation", "Manual updates"], "answerIndex": 3},
      {"id": 9, "question": "Which software development methodology is sequential, with each phase followed by the next phase and no overlap between the phases?", "choices": ["Scrum", "Lean", "Agile", "Waterfall"], "answerIndex": 3},
      {"id": 10, "question": "Which phase of software design includes gathering customer input to determine a system's desired functionality?", "choices": ["Ongoing operations", "Decommissioning", "Planning", "Requirements definition"], "answerIndex": 3},
      {"id": 11, "question": "Which technology is used to prevent cross-site request forgery (CSRF) attacks?", "choices": ["Encoding", "Tokens", "Multifactor authentication (MFA)", "Identity-based encryption (IBE)"], "answerIndex": 1},
      {"id": 12, "question": "A project manager works closely with the customer to get input on desired features and ranks them based on how critical they are for the project. Which phase of the SDLC is the project manager working on?", "choices": ["Planning", "Requirements definition", "Development", "Ongoing operations"], "answerIndex": 1},
      {"id": 13, "question": "Which web application firewall (WAF) feature protects the application servers behind it from systems sending requests?", "choices": ["Reverse proxy", "User-based filters", "Content-based filters", "Reverse IP lookup"], "answerIndex": 0},
      {"id": 14, "question": "An organization's security team has concerns about API tokens being lost or exposed to malicious actors. Which service do cloud providers offer that the organization should leverage to administer its API tokens?", "choices": ["Secrets management", "Output encoding", "Gateway", "Sandbox"], "answerIndex": 0},
      {"id": 15, "question": "Which OWASP-related testing approach inspects uncompiled source code for security flaws without executing the application, sometimes called white-box testing?", "choices": ["DAST", "SAST", "Fuzzing", "Penetration testing"], "answerIndex": 1},
      {"id": 16, "question": "Which Microsoft-developed threat modeling taxonomy covers Spoofing, Tampering, Repudiation, Information Disclosure, Denial of Service, and Elevation of Privilege?", "choices": ["STRIDE", "DREAD", "OWASP Top 10", "ATT&CK"], "answerIndex": 0},
      {"id": 17, "question": "Which deployment model builds and destroys new server instances from golden images for every update rather than patching servers in place?", "choices": ["Immutable infrastructure", "Blue-green testing", "Chaos engineering", "Rugged DevOps"], "answerIndex": 0}
    ]
  },
  "D5": {
    "id": "D5",
    "name": "Cloud Security Operations",
    "questions": [
      {"id": 1, "question": "An organization wants to gather and interpret logs from its cloud environment. Which system should the organization use for this task?", "choices": ["Simple Network Management Protocol (SNMP)", "Security Information and Event Management (SIEM)", "Business Process Management (BPM)", "Distributed System Management (DSM)"], "answerIndex": 1},
      {"id": 2, "question": "An organization with a SIEM system wants to minimize errors or missed issues due to human log analysis. Which SIEM policy should the organization use?", "choices": ["Automated analysis of metadata", "Automated analysis of data sets", "Manually generated analysis of data sets", "Manually generated analysis of metadata"], "answerIndex": 1},
      {"id": 3, "question": "An organization with a single headquarters building in New York City wants to secure its cloud infrastructure so that only users at its offices can administer its cloud resources. Which architectural concept should the organization implement?", "choices": ["Geofencing", "Two-factor authentication", "Data loss prevention", "Antivirus software"], "answerIndex": 0},
      {"id": 4, "question": "Which BC/DR term refers to a secure container that contains all the necessary documentation and resources needed to conduct a proper BC/DR response action?", "choices": ["Configuration management", "Toolkit", "Process automation", "Standard"], "answerIndex": 1},
      {"id": 5, "question": "Which purpose does an intrusion prevention system (IPS) serve when compared to an intrusion detection system (IDS)?", "choices": ["An IPS detects and stops malicious traffic, while an IDS detects and alerts about malicious traffic.", "An IPS detects and alerts about malicious traffic, while an IDS detects and stops malicious traffic.", "An IDS tells an IPS what malicious traffic it detects, and then the IPS blocks that traffic.", "An IPS tells an IDS what malicious traffic it detects, and then the IDS blocks that traffic."], "answerIndex": 0},
      {"id": 6, "question": "An analyst needs to scan hosts for misconfigurations and known security threats that could lead to a security incident. Which type of scanner will allow the analyst to check for these issues?", "choices": ["Protocol", "Address", "Port", "Vulnerability"], "answerIndex": 3},
      {"id": 7, "question": "An organization identified the need to improve the resiliency of a critical IT service to ensure access for its customers. Which ITSM process should be implemented?", "choices": ["Availability management", "Capacity management", "Incident management", "Security management"], "answerIndex": 0},
      {"id": 8, "question": "An organization lost connectivity to one of its data centers because of a power outage. What is used to measure the return to operational capability after the loss of connectivity?", "choices": ["Recovery time objective (RTO)", "Maximum tolerable downtime (MTD)", "Recovery point objective (RPO)", "Annualized loss expectancy (ALE)"], "answerIndex": 0},
      {"id": 9, "question": "A security analyst is tasked with collecting evidence related to a data breach involving monetary theft. Which action should the security analyst take when accessing the breached system?", "choices": ["Create an unencrypted backup of all data", "Create an encrypted backup of all data", "Detail and replicate all activities taken", "Document and record all activities taken"], "answerIndex": 3},
      {"id": 10, "question": "The service at a cloud provider has been interrupted. Which group should this cloud provider contact with information about the expected window for which services will be down as per a contractual agreement?", "choices": ["Customers", "Regulators", "Executives", "Employees"], "answerIndex": 0},
      {"id": 11, "question": "Which type of communication channel should be established between parties in a supply chain to be used in a disaster situation?", "choices": ["Back", "Landline", "Satellite", "Secondary"], "answerIndex": 3},
      {"id": 12, "question": "After an internal audit, an organization determined that its cloud deployment may be vulnerable to threats from external attackers. What should the organization implement to mitigate this risk?", "choices": ["Hardened virtual machines with strong access controls", "Mandatory vacation and job rotation for employees", "Real-time video surveillance monitoring of physical access to devices", "USB-blocking software to prevent unauthorized devices from being used"], "answerIndex": 0},
      {"id": 13, "question": "An organization exclusively uses Microsoft software and prefers tools that run natively on Windows. Which tool should this organization use to provide remote access to machines over an encrypted channel?", "choices": ["Remote Desktop Protocol (RDP)", "Secure Shell (SSH)", "Virtual clients", "Secure terminal access"], "answerIndex": 0},
      {"id": 14, "question": "An organization opens an office with a reception area. Visitors sign in and collect a visitor's badge, which turns from white to red after eight hours. Which security concept is the organization employing?", "choices": ["Controlled entry point", "Monitoring systems", "Vehicular approach controls", "Fire systems"], "answerIndex": 0},
      {"id": 15, "question": "An organization performs a DR exercise simulating a natural disaster where key players perform minimal actions to test the call tree and ensure contact information is up to date. Which type of testing is the organization performing?", "choices": ["Full", "Dry run", "Split", "Abuse case"], "answerIndex": 1},
      {"id": 16, "question": "After a severe storm damaged the local power grid for an organization's primary European data center, management determined this is a business continuity event since a failover site can temporarily bear the load. What should the organization leverage to return operations to the data center?", "choices": ["Uninterruptible power supply (UPS)", "Redundant array of independent disks (RAID)", "Generators", "Archives"], "answerIndex": 2},
      {"id": 17, "question": "Which backup type captures only the files that have changed since the last full or incremental backup, resetting the archive bit to optimize storage?", "choices": ["Full backup", "Copy backup", "Differential backup", "Incremental backup"], "answerIndex": 3},
      {"id": 18, "question": "A hypervisor host is placed into a special operational state so that its running virtual instances are live-migrated off before patches are applied. What is this state called?", "choices": ["Maintenance mode", "Chaos engineering", "Sandboxing", "Trunking"], "answerIndex": 0},
      {"id": 19, "question": "Which security tool passively monitors network or host traffic to detect and alert on unauthorized activity without taking action to stop it?", "choices": ["IPS", "HIPS", "IDS", "WAF"], "answerIndex": 2},
      {"id": 20, "question": "Which decoy system is intentionally exposed to lure attackers and collect threat intelligence without risking production systems?", "choices": ["Honeynet", "Honeypot", "Chokepoint", "Sandbox"], "answerIndex": 1},
      {"id": 21, "question": "Which NIST publication provides guidance specifically on establishing policies for log generation, transmission, retention, and analysis?", "choices": ["NIST 800-61", "NIST 800-92", "NIST 800-40", "NIST 800-37"], "answerIndex": 1},
      {"id": 22, "question": "During incident response, which phase focuses specifically on isolating affected systems to limit the spread and impact of an active security breach?", "choices": ["Preparation", "Detection and Analysis", "Containment", "Eradication and recovery"], "answerIndex": 2},
      {"id": 23, "question": "Which pre-configured suite of forensic tools, credentials, and memory acquisition scripts is kept ready for rapid deployment during a cloud security incident?", "choices": ["Cloud jump kit", "Chaos toolkit", "Chokepoint kit", "Sandbox kit"], "answerIndex": 0},
      {"id": 24, "question": "Which foundational security rule blocks all network traffic or access requests by default unless explicitly permitted by policy?", "choices": ["Least privilege", "Default deny", "Zero trust", "Segregation of duties"], "answerIndex": 1}
    ]
  },
  "D6": {
    "id": "D6",
    "name": "Legal, Risk and Compliance",
    "questions": [
      {"id": 1, "question": "A manager is made aware of a customer complaint about how an application collects personal and environmental information from devices it is installed on. Which document should the manager refer to in order to determine if the company has properly disclosed information about what data it collects?", "choices": ["Retention policy", "Breach notification", "Privacy notice", "Denial of service"], "answerIndex": 2},
      {"id": 2, "question": "The Department of Justice (DOJ) assesses options for a new cloud-hosted collaboration solution. What should it use to ensure that vendors are compliant with governmental regulations for data management in the US?", "choices": ["Business partnership agreement (BPA)", "Federal Risk and Authorization Management Program (FedRAMP)", "European Union Agency for Network and Information Security (ENISA)", "Nondisclosure agreement (NDA)"], "answerIndex": 1},
      {"id": 3, "question": "An EU citizen claims a company's data processing activities are out of compliance with GDPR and demands the company stop processing their personal data. What must the company do if it wishes to continue processing this personal data?", "choices": ["File an appeal with the CJEU within 60 days and continue processing the data", "Demonstrate that this data processing is a necessary business requirement", "Demonstrate that this data processing is authorized under approved standards", "File an appeal with the CJEU within 60 days and stop processing the data"], "answerIndex": 2},
      {"id": 4, "question": "During an investigation, government agents asked a security professional to collect the records stored in a database and present them to the court. Which process should the security professional use to identify and obtain that information?", "choices": ["Electronic communication", "Error correcting code (ECC) memory", "Cyclic redundancy check (CRC)", "Electronic discovery"], "answerIndex": 3},
      {"id": 5, "question": "An online store has declared a disaster because of a large storm near its primary cloud data center. The emergency plan kept it online but out of compliance with PCI DSS practices. Which party should the store keep apprised of ongoing developments and potential solutions?", "choices": ["Customers", "Developers", "Consumers", "Regulators"], "answerIndex": 3},
      {"id": 6, "question": "An organization believes a man-in-the-middle attack is possible but unlikely, though consequences would be serious if successful. The cost to reduce this risk is much more than the organization wishes to pay. Which factor will determine whether the organization decides to pay the amount to mitigate the risk?", "choices": ["Risk appetite", "Risk management", "Inherent risk", "Residual risk"], "answerIndex": 0},
      {"id": 7, "question": "Which legal requirement mandates companies in the United States to provide federal officials with data even if the data is not stored in the United States and disclosure is illegal under the laws where it is stored?", "choices": ["The Sarbanes-Oxley (SOX) Act", "The General Data Protection Regulation (GDPR)", "The Gramm-Leach-Bliley Act (GLBA)", "The Clarifying Lawful Overseas Use of Data (CLOUD) Act"], "answerIndex": 3},
      {"id": 8, "question": "Which process describes the tracking and monitoring of evidence, including who had access and what controls were used, from the time it is gathered until delivered to a court or law enforcement?", "choices": ["Audit", "Chain of custody", "Electronic discovery", "Forensic imaging"], "answerIndex": 1},
      {"id": 9, "question": "GDPR provides data subjects with various rights related to privacy. What do organizations need to do in order to acquire and use personal information under GDPR?", "choices": ["Give the data subject notice of the data use", "Have the data subject opt in for the data use", "Allow the data subject to opt out of the data use", "Get the data subject to sign an agreement for the data use"], "answerIndex": 1},
      {"id": 10, "question": "An organization has devised a new use for the personal data it stores about its customers. What should the organization do according to the Generally Accepted Privacy Principles (GAPP)?", "choices": ["Notify users once the updated data processing is in place", "Obtain additional consent before using personal data in a different way", "Take no further action as users have already consented to data processing", "Remove the data processing clause from its policy to avoid a conflict"], "answerIndex": 1},
      {"id": 11, "question": "Which type of analysis compares a control analysis against a baseline standard?", "choices": ["Privacy impact analysis", "Gap analysis", "Risk analysis", "Business impact analysis"], "answerIndex": 1},
      {"id": 12, "question": "Which type of statement issued by an auditor indicates that an organization did not disclose enough information to perform a fair audit?", "choices": ["Income", "Adverse opinion", "Compliance", "Scope limitation"], "answerIndex": 3},
      {"id": 13, "question": "Which risk management strategy involves changing business practices to eliminate the potential of an enterprise risk?", "choices": ["Acceptance", "Transference", "Mitigation", "Avoidance"], "answerIndex": 3}
    ]
  }
};
